#!/bin/bash
## postBuild configuration script for Binder (https://mybinder.org/)
conda install 'gcc<5.0|>=9.0'
pip install -r ttpy_repo.txt
pip install -e .

# Google analytics extension
## Original version:
##pip install nbgoogleanalytics
## Let Google Analytics manage DNT:
pip install git+https://github.com/yuvipanda/nbgoogleanalytics.git@36114604ba3f3054bf40c608d7d100ee9857d58c#egg=nbgoogleanalytics
sed -i -e '15,19d;29d' /srv/conda/lib/python3.6/site-packages/nbgoogleanalytics/static/main.js
##--
jupyter nbextension install --py --sys-prefix nbgoogleanalytics
jupyter nbextension enable --py --sys-prefix nbgoogleanalytics
jupyter serverextension enable --sys-prefix nbgoogleanalytics
jupyter notebook --generate-config
echo 'c.GoogleAnalytics.tracking_id="UA-121211479-1"' >> $HOME/.jupyter/jupyter_notebook_config.py
